"""
update_prices.py
Fetches latest closing prices for all 200 NSE stocks via yfinance
and writes prices.json. Runs daily via GitHub Actions at 3:30 PM IST.
"""

import json
import yfinance as yf
from datetime import datetime, timezone, timedelta

TICKERS = [
    "NTPC",
    "POWERGRID",
    "COALINDIA",
    "TATAPOWER",
    "ADANIGREEN",
    "ADANIPOWER",
    "CESC",
    "TORNTPOWER",
    "NHPC",
    "SJVN",
    "BPCL",
    "IOC",
    "HINDPETRO",
    "GAIL",
    "PETRONET",
    "OIL",
    "ONGC",
    "RELIANCE",
    "IGL",
    "MGL",
    "HDFCBANK",
    "ICICIBANK",
    "KOTAKBANK",
    "SBIN",
    "AXISBANK",
    "INDUSINDBK",
    "BANDHANBNK",
    "FEDERALBNK",
    "IDFCFIRSTB",
    "AUBANK",
    "BAJFINANCE",
    "BAJAJFINSV",
    "CHOLAFIN",
    "MUTHOOTFIN",
    "HDFCLIFE",
    "SBILIFE",
    "ICICIGI",
    "LICI",
    "PFC",
    "RECLTD",
    "INFY",
    "TCS",
    "WIPRO",
    "HCLTECH",
    "TECHM",
    "LTIM",
    "MPHASIS",
    "COFORGE",
    "PERSISTENT",
    "KPIT",
    "CYIENT",
    "ZENSARTECH",
    "BSOFT",
    "TATAELXSI",
    "INTELLECT",
    "RATEGAIN",
    "NAUKRI",
    "POLICYBZR",
    "MAPMYINDIA",
    "HAPPSTMNDS",
    "KECINTER",
    "ABB",
    "SIEMENS",
    "BHEL",
    "LTTS",
    "LT",
    "CUMMINSIND",
    "THERMAX",
    "AIAENG",
    "GRINDWELL",
    "ELGIEQUIP",
    "KALPATPOWR",
    "GMRINFRA",
    "IRB",
    "KNRCON",
    "NCC",
    "ENGINERSIN",
    "RVNL",
    "IRFC",
    "TITAGARH",
    "HINDUNILVR",
    "ITC",
    "NESTLEIND",
    "BRITANNIA",
    "DABUR",
    "MARICO",
    "GODREJCP",
    "EMAMILTD",
    "COLPAL",
    "TATACONSUM",
    "VBL",
    "DMART",
    "TRENT",
    "ABFRL",
    "TITAN",
    "KALYANKJIL",
    "BATAINDIA",
    "PAGEIND",
    "PIDILITIND",
    "ASIANPAINT",
    "SUNPHARMA",
    "DRREDDY",
    "CIPLA",
    "DIVISLAB",
    "AUROPHARMA",
    "LUPIN",
    "TORNTPHARM",
    "ALKEM",
    "IPCALAB",
    "ABBOTINDIA",
    "PFIZER",
    "GLAXO",
    "APOLLOHOSP",
    "MAXHEALTH",
    "FORTIS",
    "METROPOLIS",
    "LALPATHLAB",
    "POLYMED",
    "MEDANTA",
    "MANKIND",
    "MARUTI",
    "TATAMOTORS",
    "M&M",
    "BAJAJ-AUTO",
    "HEROMOTOCO",
    "EICHERMOT",
    "TVSMOTORS",
    "ASHOKLEY",
    "TIINDIA",
    "MOTHERSON",
    "BHARATFORG",
    "BOSCHLTD",
    "EXIDEIND",
    "AMARAJABAT",
    "MRF",
    "APOLLOTYRE",
    "CEATLTD",
    "BALKRISIND",
    "SUNDRMFAST",
    "SUPRAJIT",
    "TATASTEEL",
    "JSWSTEEL",
    "HINDALCO",
    "VEDL",
    "SAIL",
    "NMDC",
    "HINDCOPPER",
    "NALCO",
    "MOIL",
    "APLAPOLLO",
    "RATNAMANI",
    "JSWINFRA",
    "ADANIPORTS",
    "ACC",
    "AMBUJACEM",
    "ULTRACEMCO",
    "SHREECEM",
    "RAMCOCEM",
    "JKCEMENT",
    "DALMIACEM",
    "HAL",
    "BEL",
    "BEML",
    "COCHINSHIP",
    "MAZDOCK",
    "GRSE",
    "PARAS",
    "DATAPATT",
    "MIDHANI",
    "ASTRAMICRO",
    "MTAR",
    "SOLARINDS",
    "ZENTEC",
    "IDEAFORGE",
    "APOLLOMICRO",
    "DCX",
    "DYNAMATECH",
    "ELID",
    "NIBE",
    "HARIOMPIPE",
    "AARTIIND",
    "DEEPAKNTR",
    "NAVINFLUOR",
    "SRF",
    "TATACHEM",
    "GNFC",
    "GSFC",
    "COROMANDEL",
    "UPL",
    "RALLIS",
    "SUPREMEIND",
    "ASTRAL",
    "CLEAN",
    "FINEORG",
    "GALAXYSURF",
    "VINATI",
    "PRINCEPIPE",
    "APOLLOPIPE",
    "FINPIPE",
    "GUJGASLTD",
]

def fetch_prices(tickers):
    prices = {}
    failed = []
    for ticker in tickers:
        yf_symbol = ticker + ".NS"
        try:
            data = yf.Ticker(yf_symbol)
            info = data.fast_info
            price = round(info.last_price, 2) if info.last_price else None
            if price:
                prices[ticker] = {
                    "cmp": price,
                    "prev_close": round(info.previous_close, 2) if info.previous_close else None,
                    "day_high": round(info.day_high, 2) if info.day_high else None,
                    "day_low": round(info.day_low, 2) if info.day_low else None,
                    "week_52_high": round(info.year_high, 2) if info.year_high else None,
                    "week_52_low": round(info.year_low, 2) if info.year_low else None,
                    "change_pct": round((price - info.previous_close) / info.previous_close * 100, 2) if info.previous_close else None,
                }
                print(f"  ✓ {ticker}: ₹{price}")
            else:
                failed.append(ticker)
                print(f"  ✗ {ticker}: no price")
        except Exception as e:
            failed.append(ticker)
            print(f"  ✗ {ticker}: {e}")
    return prices, failed

def main():
    IST = timezone(timedelta(hours=5, minutes=30))
    now_ist = datetime.now(IST)
    print(f"\nPrice update — {now_ist.strftime('%d %b %Y %H:%M IST')}")
    prices, failed = fetch_prices(TICKERS)
    output = {
        "updated_at": now_ist.isoformat(),
        "updated_at_readable": now_ist.strftime("%d %b %Y %H:%M IST"),
        "prices": prices,
        "failed": failed,
        "total": len(prices),
    }
    with open("prices.json", "w") as f:
        json.dump(output, f, indent=2)
    print(f"\n✓ prices.json written — {len(prices)} tickers, {len(failed)} failed")
    if failed:
        print(f"✗ Failed: {', '.join(failed)}")

if __name__ == "__main__":
    main()
